// Code generated by protoc-gen-go. DO NOT EDIT.
// source: image.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ImageUploadReq struct {
	// Types that are valid to be assigned to Pkt:
	//	*ImageUploadReq_Name
	//	*ImageUploadReq_MetadataJson
	//	*ImageUploadReq_RootfsTarball
	Pkt                  isImageUploadReq_Pkt `protobuf_oneof:"pkt"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ImageUploadReq) Reset()         { *m = ImageUploadReq{} }
func (m *ImageUploadReq) String() string { return proto.CompactTextString(m) }
func (*ImageUploadReq) ProtoMessage()    {}
func (*ImageUploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{0}
}

func (m *ImageUploadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageUploadReq.Unmarshal(m, b)
}
func (m *ImageUploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageUploadReq.Marshal(b, m, deterministic)
}
func (m *ImageUploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageUploadReq.Merge(m, src)
}
func (m *ImageUploadReq) XXX_Size() int {
	return xxx_messageInfo_ImageUploadReq.Size(m)
}
func (m *ImageUploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageUploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImageUploadReq proto.InternalMessageInfo

type isImageUploadReq_Pkt interface {
	isImageUploadReq_Pkt()
}

type ImageUploadReq_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type ImageUploadReq_MetadataJson struct {
	MetadataJson []byte `protobuf:"bytes,2,opt,name=metadataJson,proto3,oneof"`
}

type ImageUploadReq_RootfsTarball struct {
	RootfsTarball []byte `protobuf:"bytes,3,opt,name=rootfsTarball,proto3,oneof"`
}

func (*ImageUploadReq_Name) isImageUploadReq_Pkt() {}

func (*ImageUploadReq_MetadataJson) isImageUploadReq_Pkt() {}

func (*ImageUploadReq_RootfsTarball) isImageUploadReq_Pkt() {}

func (m *ImageUploadReq) GetPkt() isImageUploadReq_Pkt {
	if m != nil {
		return m.Pkt
	}
	return nil
}

func (m *ImageUploadReq) GetName() string {
	if x, ok := m.GetPkt().(*ImageUploadReq_Name); ok {
		return x.Name
	}
	return ""
}

func (m *ImageUploadReq) GetMetadataJson() []byte {
	if x, ok := m.GetPkt().(*ImageUploadReq_MetadataJson); ok {
		return x.MetadataJson
	}
	return nil
}

func (m *ImageUploadReq) GetRootfsTarball() []byte {
	if x, ok := m.GetPkt().(*ImageUploadReq_RootfsTarball); ok {
		return x.RootfsTarball
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ImageUploadReq) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ImageUploadReq_Name)(nil),
		(*ImageUploadReq_MetadataJson)(nil),
		(*ImageUploadReq_RootfsTarball)(nil),
	}
}

type ImageUploadRes struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageUploadRes) Reset()         { *m = ImageUploadRes{} }
func (m *ImageUploadRes) String() string { return proto.CompactTextString(m) }
func (*ImageUploadRes) ProtoMessage()    {}
func (*ImageUploadRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{1}
}

func (m *ImageUploadRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageUploadRes.Unmarshal(m, b)
}
func (m *ImageUploadRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageUploadRes.Marshal(b, m, deterministic)
}
func (m *ImageUploadRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageUploadRes.Merge(m, src)
}
func (m *ImageUploadRes) XXX_Size() int {
	return xxx_messageInfo_ImageUploadRes.Size(m)
}
func (m *ImageUploadRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageUploadRes.DiscardUnknown(m)
}

var xxx_messageInfo_ImageUploadRes proto.InternalMessageInfo

func (m *ImageUploadRes) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ImageDeleteReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageDeleteReq) Reset()         { *m = ImageDeleteReq{} }
func (m *ImageDeleteReq) String() string { return proto.CompactTextString(m) }
func (*ImageDeleteReq) ProtoMessage()    {}
func (*ImageDeleteReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{2}
}

func (m *ImageDeleteReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageDeleteReq.Unmarshal(m, b)
}
func (m *ImageDeleteReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageDeleteReq.Marshal(b, m, deterministic)
}
func (m *ImageDeleteReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageDeleteReq.Merge(m, src)
}
func (m *ImageDeleteReq) XXX_Size() int {
	return xxx_messageInfo_ImageDeleteReq.Size(m)
}
func (m *ImageDeleteReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageDeleteReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImageDeleteReq proto.InternalMessageInfo

func (m *ImageDeleteReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ImageDeleteRes struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageDeleteRes) Reset()         { *m = ImageDeleteRes{} }
func (m *ImageDeleteRes) String() string { return proto.CompactTextString(m) }
func (*ImageDeleteRes) ProtoMessage()    {}
func (*ImageDeleteRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{3}
}

func (m *ImageDeleteRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageDeleteRes.Unmarshal(m, b)
}
func (m *ImageDeleteRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageDeleteRes.Marshal(b, m, deterministic)
}
func (m *ImageDeleteRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageDeleteRes.Merge(m, src)
}
func (m *ImageDeleteRes) XXX_Size() int {
	return xxx_messageInfo_ImageDeleteRes.Size(m)
}
func (m *ImageDeleteRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageDeleteRes.DiscardUnknown(m)
}

var xxx_messageInfo_ImageDeleteRes proto.InternalMessageInfo

func (m *ImageDeleteRes) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ImageListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageListReq) Reset()         { *m = ImageListReq{} }
func (m *ImageListReq) String() string { return proto.CompactTextString(m) }
func (*ImageListReq) ProtoMessage()    {}
func (*ImageListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{4}
}

func (m *ImageListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageListReq.Unmarshal(m, b)
}
func (m *ImageListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageListReq.Marshal(b, m, deterministic)
}
func (m *ImageListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageListReq.Merge(m, src)
}
func (m *ImageListReq) XXX_Size() int {
	return xxx_messageInfo_ImageListReq.Size(m)
}
func (m *ImageListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ImageListReq proto.InternalMessageInfo

type ImageListRes struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MetadataJson         []byte   `protobuf:"bytes,2,opt,name=metadataJson,proto3" json:"metadataJson,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageListRes) Reset()         { *m = ImageListRes{} }
func (m *ImageListRes) String() string { return proto.CompactTextString(m) }
func (*ImageListRes) ProtoMessage()    {}
func (*ImageListRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_9624c68e2b547544, []int{5}
}

func (m *ImageListRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageListRes.Unmarshal(m, b)
}
func (m *ImageListRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageListRes.Marshal(b, m, deterministic)
}
func (m *ImageListRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageListRes.Merge(m, src)
}
func (m *ImageListRes) XXX_Size() int {
	return xxx_messageInfo_ImageListRes.Size(m)
}
func (m *ImageListRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageListRes.DiscardUnknown(m)
}

var xxx_messageInfo_ImageListRes proto.InternalMessageInfo

func (m *ImageListRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ImageListRes) GetMetadataJson() []byte {
	if m != nil {
		return m.MetadataJson
	}
	return nil
}

func init() {
	proto.RegisterType((*ImageUploadReq)(nil), "api.ImageUploadReq")
	proto.RegisterType((*ImageUploadRes)(nil), "api.ImageUploadRes")
	proto.RegisterType((*ImageDeleteReq)(nil), "api.ImageDeleteReq")
	proto.RegisterType((*ImageDeleteRes)(nil), "api.ImageDeleteRes")
	proto.RegisterType((*ImageListReq)(nil), "api.ImageListReq")
	proto.RegisterType((*ImageListRes)(nil), "api.ImageListRes")
}

func init() {
	proto.RegisterFile("image.proto", fileDescriptor_9624c68e2b547544)
}

var fileDescriptor_9624c68e2b547544 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbb, 0xff, 0x34, 0xf9, 0xe3, 0x18, 0x0b, 0x8e, 0x22, 0x21, 0xa7, 0x12, 0x8a, 0xe4,
	0xb4, 0x48, 0xf5, 0xe6, 0xad, 0x88, 0x54, 0xf1, 0xb4, 0xe8, 0xc5, 0xdb, 0x94, 0xae, 0xb2, 0x98,
	0x74, 0xb7, 0xd9, 0xbd, 0xf9, 0x69, 0xfc, 0xa6, 0x92, 0x4d, 0xac, 0x5d, 0x8d, 0xc7, 0xf9, 0xe5,
	0xe5, 0xcd, 0x9b, 0xc7, 0xc2, 0xa1, 0xaa, 0xe9, 0x55, 0x72, 0xd3, 0x68, 0xa7, 0x31, 0x22, 0xa3,
	0x8a, 0x77, 0x98, 0xdc, 0xb5, 0xec, 0xc9, 0x54, 0x9a, 0xd6, 0x42, 0x6e, 0xf1, 0x14, 0xc6, 0x1b,
	0xaa, 0x65, 0xc6, 0xa6, 0xac, 0x3c, 0x58, 0x8e, 0x84, 0x9f, 0x70, 0x06, 0x69, 0x2d, 0x1d, 0xad,
	0xc9, 0xd1, 0xbd, 0xd5, 0x9b, 0xec, 0xdf, 0x94, 0x95, 0xe9, 0x72, 0x24, 0x02, 0x8a, 0xe7, 0x70,
	0xd4, 0x68, 0xed, 0x5e, 0xec, 0x23, 0x35, 0x2b, 0xaa, 0xaa, 0x2c, 0xea, 0x65, 0x21, 0x5e, 0xc4,
	0x10, 0x99, 0x37, 0x57, 0x94, 0x3f, 0x96, 0x5b, 0x3c, 0x83, 0xa4, 0x91, 0xd4, 0x2e, 0xf0, 0xeb,
	0x45, 0x3f, 0x15, 0xb3, 0x5e, 0x79, 0x23, 0x2b, 0xe9, 0x64, 0x1b, 0x13, 0xf7, 0x63, 0x76, 0x21,
	0x77, 0x7e, 0x5f, 0xaa, 0xbf, 0xfd, 0x26, 0x90, 0x7a, 0xe5, 0x83, 0xb2, 0x4e, 0xc8, 0x6d, 0x71,
	0x1b, 0xcc, 0x76, 0xc8, 0x1d, 0x8b, 0xa1, 0x0a, 0xc2, 0x02, 0xe6, 0x1f, 0x0c, 0x62, 0x6f, 0x84,
	0x57, 0x90, 0x74, 0x67, 0xe1, 0x09, 0x27, 0xa3, 0x78, 0xd8, 0x72, 0x3e, 0x00, 0x6d, 0xc9, 0x70,
	0x0e, 0x49, 0x17, 0x7e, 0xff, 0xaf, 0xdd, 0xd1, 0xf9, 0x00, 0xb4, 0xc8, 0x61, 0xdc, 0xc6, 0xc6,
	0xe3, 0xef, 0x8f, 0xfd, 0x59, 0xf9, 0x2f, 0x64, 0x2f, 0xd8, 0xe2, 0xff, 0x73, 0xcc, 0xaf, 0xc9,
	0xa8, 0x55, 0xe2, 0xdf, 0xc1, 0xe5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0x04, 0xa7, 0xc1,
	0x16, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ImageClient is the client API for Image service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImageClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (Image_UploadClient, error)
	Delete(ctx context.Context, in *ImageDeleteReq, opts ...grpc.CallOption) (*ImageDeleteRes, error)
	List(ctx context.Context, in *ImageListReq, opts ...grpc.CallOption) (Image_ListClient, error)
}

type imageClient struct {
	cc grpc.ClientConnInterface
}

func NewImageClient(cc grpc.ClientConnInterface) ImageClient {
	return &imageClient{cc}
}

func (c *imageClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Image_UploadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Image_serviceDesc.Streams[0], "/api.Image/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageUploadClient{stream}
	return x, nil
}

type Image_UploadClient interface {
	Send(*ImageUploadReq) error
	CloseAndRecv() (*ImageUploadRes, error)
	grpc.ClientStream
}

type imageUploadClient struct {
	grpc.ClientStream
}

func (x *imageUploadClient) Send(m *ImageUploadReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageUploadClient) CloseAndRecv() (*ImageUploadRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ImageUploadRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageClient) Delete(ctx context.Context, in *ImageDeleteReq, opts ...grpc.CallOption) (*ImageDeleteRes, error) {
	out := new(ImageDeleteRes)
	err := c.cc.Invoke(ctx, "/api.Image/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageClient) List(ctx context.Context, in *ImageListReq, opts ...grpc.CallOption) (Image_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Image_serviceDesc.Streams[1], "/api.Image/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Image_ListClient interface {
	Recv() (*ImageListRes, error)
	grpc.ClientStream
}

type imageListClient struct {
	grpc.ClientStream
}

func (x *imageListClient) Recv() (*ImageListRes, error) {
	m := new(ImageListRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServer is the server API for Image service.
type ImageServer interface {
	Upload(Image_UploadServer) error
	Delete(context.Context, *ImageDeleteReq) (*ImageDeleteRes, error)
	List(*ImageListReq, Image_ListServer) error
}

// UnimplementedImageServer can be embedded to have forward compatible implementations.
type UnimplementedImageServer struct {
}

func (*UnimplementedImageServer) Upload(srv Image_UploadServer) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (*UnimplementedImageServer) Delete(ctx context.Context, req *ImageDeleteReq) (*ImageDeleteRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedImageServer) List(req *ImageListReq, srv Image_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterImageServer(s *grpc.Server, srv ImageServer) {
	s.RegisterService(&_Image_serviceDesc, srv)
}

func _Image_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServer).Upload(&imageUploadServer{stream})
}

type Image_UploadServer interface {
	SendAndClose(*ImageUploadRes) error
	Recv() (*ImageUploadReq, error)
	grpc.ServerStream
}

type imageUploadServer struct {
	grpc.ServerStream
}

func (x *imageUploadServer) SendAndClose(m *ImageUploadRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageUploadServer) Recv() (*ImageUploadReq, error) {
	m := new(ImageUploadReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Image_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Image/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServer).Delete(ctx, req.(*ImageDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Image_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageListReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServer).List(m, &imageListServer{stream})
}

type Image_ListServer interface {
	Send(*ImageListRes) error
	grpc.ServerStream
}

type imageListServer struct {
	grpc.ServerStream
}

func (x *imageListServer) Send(m *ImageListRes) error {
	return x.ServerStream.SendMsg(m)
}

var _Image_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Image",
	HandlerType: (*ImageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _Image_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Image_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _Image_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "image.proto",
}
